version: '3.8'
services:
  postgres:
    image: postgres:15.2-alpine
    networks:
      - postgres
    ports:
      - 5432:5432
    volumes: 
      - postgresql:/var/lib/postgresql/data
    env_file:
      - docker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -h postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:6.21
    networks:
      - postgres
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - docker.env

  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: 'sh -c "npm run migration:run && npm run start:dev"'
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes :
  postgresql:
  pgadmin:
